
title: Hsiangchun Wang CV
url: 'http://webjeda.com'
baseurl: '/hsiangchunwang.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name:Hsiang-Chun Wang
tagline:Senior graduate student @Tsinghua University
pic:hsiangchunwangprofile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:wangchun@hotmail.com.tw
phone:0978206975(TW)
 #do not add http://
linkedin:Hsiang-Chun Wang
#Update all the sections by editing the files inside _includes folder.
